import Head from "next/head";
import styles from "../styles/Home.module.css";
import wallpaySDK from "./wallpay";
import { useRouter } from "next/router";

export const BuyButton = () => {
  const { onOpenPaymentModal } = wallpaySDK.usePayment();
  const { walletIsConnected, onOpenModal, walletAddress } =
    wallpaySDK.useWallets();
  const router = useRouter();

  const triggerLogin = () => {
    onOpenModal();
  };

  // FOR THIS ERC1155 CONTRACT EXAMPLE, WE NEED THE FOLLOWING PARAMETERS:
  // FOR MINTING:
  // [ tokenId, amount ]
  // FOR TRANSFERING (FIAT PAYMENT):
  // [ tokenId, amount, recipientAddress ]

  // FOR A ERC721 CONTRACT EXAMPLE, WE WOULD JUST USE THE FOLLOWING PARAMETERS:
  // FOR MINTING:
  // [ amount ]
  // FOR TRANSFERING (FIAT PAYMENT):
  // [ amount, recipientAddress ]

  // transferParams AND mintParams ARE FREE TO FOLLOW YOUR CONTRACT SPECIFICATION

  let unitPrice = 5; // IN CRYPTO CURRENCY
  let quantity = 2; 
  let myTokenId = 4; 

  const nftData = {
    unitPrice: unitPrice,
    amount: quantity,
    itemName: "A+great+NFT",
    itemImage: "https://via.placeholder.com/150x200?text=A+great+NFT",
    transferParams: {
      tokenId: myTokenId,
      amount: quantity,
      walletAddress: walletAddress,
    },
    mintParams: { tokenId: myTokenId, amount: quantity },
  };

  const triggerPayment = async () => {
    if (walletIsConnected) {
      onOpenPaymentModal(nftData);
    } else {
      triggerLogin();
    }
  };

  return (
    <>
      <button
        onClick={triggerPayment}
        style={{
          fontSize: 24,
          backgroundColor: "#e3e3e3",
          padding: 16,
          borderRadius: 8,
          border: "none",
          fontWeight: "bold",
        }}
      >
        WALLPAY PAYMENT
      </button>
      <wallpaySDK.HandleConfirmCredit
        router={router}
        imageURL={nftData.itemImage}
      />
    </>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BuyButton />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://goblockchain.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Wallpay
        </a>
      </footer>
    </div>
  );
}
